src/main/java/it/univpm/advprog/singers/model/dao/AlbumDao.java
package it.univpm.advprog.singers.model.dao;

import java.util.List;

import org.hibernate.Session;

import it.univpm.advprog.singers.model.entities.Album;
import it.univpm.advprog.singers.model.entities.Singer;

public interface AlbumDao {
	Session getSession();
	public void setSession(Session session);

	
	List<Album> findAll();
	
	Album findById(Long id);

	Album create(String title);
	
	Album create(String title, Singer singer);
	
	Album update(Album album);
	
	void delete(Album album);


}

src/main/java/it/univpm/advprog/singers/model/dao/AlbumDaoDefault.java
package it.univpm.advprog.singers.model.dao;

import java.util.List;

import org.springframework.stereotype.Repository;

import it.univpm.advprog.singers.model.entities.Album;
import it.univpm.advprog.singers.model.entities.Singer;

//@Transactional
@Repository("albumDao")
public class AlbumDaoDefault extends DefaultDao implements AlbumDao {
	
	@Override
//	@Transactional(readOnly = true)
	public List<Album> findAll() {
		return getSession().
			createQuery("from Album a", Album.class).
			getResultList();
	}

	@Override
//	@Transactional(readOnly = true)
	public Album findById(Long id) {
		return getSession().find(Album.class, id);
	}

	@Override
//	@Transactional
	public void delete(Album album) {
		this.getSession().delete(album);
	}

	@Override
//	@Transactional
	public Album create(String title) {
		return this.create(title, null);
	}

	@Override
//	@Transactional
	public Album create(String title, Singer singer) {
		Album album = new Album();
		album.setTitle(title);
		album.setSinger(singer);
		this.getSession().save(album);
		return album;
	}

	@Override
//	@Transactional
	public Album update(Album album) {
		return (Album)this.getSession().merge(album);
	}

}

src/main/java/it/univpm/advprog/singers/model/dao/DefaultDao.java
package it.univpm.advprog.singers.model.dao;

import javax.annotation.Resource;

import org.hibernate.HibernateException;
import org.hibernate.Session;
import org.hibernate.SessionFactory;

public abstract class DefaultDao {
		
	private SessionFactory sessionFactory;
	private Session session;

	public SessionFactory getSessionFactory() {
		return sessionFactory;
	}

	@Resource(name = "sessionFactory")
	public void setSessionFactory(SessionFactory sessionFactory) {
		this.sessionFactory = sessionFactory;
	}

	public void setSession(Session session) {
		// added to allow a single thread session sharing scheme
		this.session = session; 
	}
	
	public Session getSession() {
		// 1. in case a shared session exists, return it (e.g. data generation script)
		Session session = this.session;
		if (session == null) {
			// 2. otherwise generate a new session using the factory (e.g. Spring MVC)
			try {
				session = this.sessionFactory.getCurrentSession();
			} catch (HibernateException ex) {
				// error getting current session, try to open a new one
				session = this.sessionFactory.openSession();
			}
		}
		return session;
			
//		Session curr = sessionFactory.getCurrentSession();
//		return curr;
	}

}

src/main/java/it/univpm/advprog/singers/model/dao/InstrumentDao.java
package it.univpm.advprog.singers.model.dao;

import java.util.List;

import org.hibernate.Session;

import it.univpm.advprog.singers.model.entities.Instrument;

public interface InstrumentDao {
	
	Session getSession();
	public void setSession(Session session);

	Instrument findByName(String name);
	
	List<Instrument> findAll();

	Instrument findById(String id);

	Instrument create(String id, String name, String family);

	Instrument update(Instrument instrument);

	void delete(Instrument contact);
	
}

src/main/java/it/univpm/advprog/singers/model/dao/InstrumentDaoDefault.java
package it.univpm.advprog.singers.model.dao;

import java.util.List;

import org.springframework.stereotype.Repository;

import it.univpm.advprog.singers.model.entities.Instrument;

//@Transactional
@Repository("instrumentDao")
public class InstrumentDaoDefault extends DefaultDao implements InstrumentDao  {

	@Override
	public List<Instrument> findAll() {
		return this.getSession().createQuery("FROM Instrument i", Instrument.class).getResultList();
	}

	@Override
	public Instrument findById(String id) {
		return this.getSession().find(Instrument.class, id);
	}

	@Override
	public Instrument update(Instrument instrument) {
		return (Instrument)this.getSession().merge(instrument);
	}

	@Override
	public void delete(Instrument instrument) {
		this.getSession().delete(instrument);
	
	}

	@Override
	public Instrument create(String id, String name, String family) {
		Instrument i = new Instrument();
		i.setInstrumentId(id);
		i.setName(name);
		i.setFamily(family);
		this.getSession().save(i);
		return i;
	}

	
	@Override
	public Instrument findByName(String name) {
		return this.getSession().createQuery("FROM Instrument i WHERE i.name = :name", Instrument.class).setParameter("name", name).getSingleResult();
	}
}

src/main/java/it/univpm/advprog/singers/model/dao/RoleDao.java
package it.univpm.advprog.singers.model.dao;

import org.hibernate.Session;

import it.univpm.advprog.singers.model.entities.Role;

public interface RoleDao {
	Session getSession();
	public void setSession(Session session);

	Role create(String name);
	
	Role update(Role role);
	
	void delete(Role role);

}

src/main/java/it/univpm/advprog/singers/model/dao/RoleDaoDefault.java
package it.univpm.advprog.singers.model.dao;

import org.springframework.stereotype.Repository;

import it.univpm.advprog.singers.model.entities.Role;

//@Transactional
@Repository
public class RoleDaoDefault extends DefaultDao implements RoleDao {

	@Override
	public Role create(String name) {
		Role r = new Role();
		r.setName(name);
		this.getSession().save(r);
		
		return r;
	}

	@Override
	public Role update(Role role) {
		return (Role)this.getSession().merge(role);
	}

	@Override
	public void delete(Role role) {
		this.getSession().delete(role);
	}

}

src/main/java/it/univpm/advprog/singers/model/dao/SingerDao.java
package it.univpm.advprog.singers.model.dao;

import java.time.LocalDate;
import java.util.List;
import java.util.Set;

import org.hibernate.Session;

import it.univpm.advprog.singers.model.entities.Album;
import it.univpm.advprog.singers.model.entities.Singer;

public interface SingerDao {
	
	public Session getSession();
	public void setSession(Session session);
		
	List<Singer> findAll();

	List<Singer> findAllWithAlbum();
	
	Singer findById(Long id);

	Singer create(String string, String string2, LocalDate birthdate);
	
	Singer update(Singer singer);
	
	void delete(Singer contact);
	
	Set<Album> getAlbums(Singer singer);

}

src/main/java/it/univpm/advprog/singers/model/dao/UserDetailsDao.java
package it.univpm.advprog.singers.model.dao;

import org.hibernate.Session;
import org.springframework.security.crypto.password.PasswordEncoder;

import it.univpm.advprog.singers.model.entities.User;


public interface UserDetailsDao {
	Session getSession();
	public void setSession(Session session);

	
	User findUserByUsername(String username);
	
	User create(String username, String password, boolean isEnabled);
	
	User update(User user);
	
	void delete(User user);

	public String encryptPassword(String password);
	
	void setPasswordEncoder(PasswordEncoder passwordEncoder);
	
	PasswordEncoder getpasswordEncoder();
}

src/main/java/it/univpm/advprog/singers/model/entities/Singer.java
package it.univpm.advprog.singers.model.entities;

import java.io.Serializable;
import java.time.LocalDate;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Convert;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.Version;

import it.univpm.advprog.singers.utils.LocalDateAttributeConverter;

@Entity
@Table(name = "singer")
@NamedQueries({
    @NamedQuery(name="Singer.findAllWithAlbum",
     query="select distinct s from Singer s " +
        "left join fetch s.albums a " +
        "left join fetch s.instruments i")
})
public class Singer implements Serializable {

	private static final long serialVersionUID = 1847253395173328425L;

	private Long id;
	private String firstName;
	private String lastName;
	private LocalDate birthDate;
	private int version;
	
	private Set<Album> albums = new HashSet<Album>();
	private Set<Instrument> instruments = new HashSet<Instrument>();

	public void setId(Long id) {
		this.id = id;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ID")
	public Long getId() {
		return this.id;
	}

	@Version
	@Column(name = "VERSION")
	public int getVersion() {
		return version;
	}

	@Column(name = "FIRST_NAME")
	public String getFirstName() {
		return this.firstName;
	}

	@Column(name = "LAST_NAME")
	public String getLastName() {
		return this.lastName;
	}

	@Column(name = "BIRTH_DATE")
	@Convert(converter = LocalDateAttributeConverter.class)
	public LocalDate getBirthDate() {
		return birthDate;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public void setBirthDate(LocalDate birthDate) {
		this.birthDate = birthDate;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public String toString() {
		return "Singer - Id: " + id + ", First name: " + firstName + ", Last name: " + lastName + ", Birthday: "
				+ birthDate;
	}

	/**
	 * Note that this property is derived from mapped fields, but it's not mapped itself in the db (thus the @Transient annotation)
	 * 
	 * @return The full name of the singer
	 */
	@Transient
	public String getFullName() {
		return (this.firstName + " " + this.lastName).trim();
	}
	
	@OneToMany(mappedBy="singer", cascade=CascadeType.ALL,
			orphanRemoval=true)
	public Set<Album> getAlbums() {
		return this.albums;
	}
	
	public void addAlbum(Album album) {
		album.setSinger(this);
		this.albums.add(album);
		
	}
	
	public void setAlbums(Set<Album> albums) {
		this.albums = albums;
	}
	
	@ManyToMany(fetch = FetchType.EAGER,        
			cascade =
	        {
	                CascadeType.DETACH,
	                CascadeType.MERGE,
	                CascadeType.REFRESH,
	                CascadeType.PERSIST
	        })
	@JoinTable(name="singer_instrument",
		 joinColumns = @JoinColumn(name = "SINGER_ID", nullable = false,
                 updatable = false), 
		 inverseJoinColumns = @JoinColumn(name = "INSTRUMENT_ID", nullable = false,
         updatable = false)) 
	public Set<Instrument> getInstruments() {
		return this.instruments;
	}
	
	public void addInstrument(Instrument i) {
		this.instruments.add(i);
		i.getSingers().add(this); // NB notare che non usiamo l'utility method addSinger
	}
	
	public void removeInstrument(Instrument i) {
		this.instruments.remove(i);
		i.getSingers().remove(this);
	}
	
	public void setInstruments(Set<Instrument> instruments) {
		this.instruments = instruments;
	}
	
}

src/main/java/it/univpm/advprog/singers/controller/AlbumController.java
package it.univpm.advprog.singers.controller;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;

import it.univpm.advprog.singers.model.entities.Album;
import it.univpm.advprog.singers.services.AlbumService;

@RequestMapping("/albums")
@Controller
public class AlbumController {
	
	private AlbumService albumService;
	
	@GetMapping(value="/list")
	public String list(Model uiModel) {
		
		List<Album> albums = this.albumService.findAll();
		uiModel.addAttribute("albums", albums);
		
		return "albums/list";
	}
	
	@GetMapping(value="/add")
	public String add(Model uiModel) {
		
		uiModel.addAttribute("album", new Album());
		
		return "albums/form";
	}
	
	@PostMapping(value="/save")
	public String save(@ModelAttribute("album") Album album, BindingResult bindingResult) {
		
		this.albumService.update(album);
		
		return "redirect:/albums/list";
	}
	
	
	@Autowired
	public void setAlbumService(AlbumService albumService) {
		this.albumService = albumService;
	}
}

src/main/java/it/univpm/advprog/singers/controller/HomeController.java
package it.univpm.advprog.singers.controller;

import java.text.DateFormat;
import java.util.Date;
import java.util.Locale;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@Controller
public class HomeController {
	
	@Autowired
	String appName; // = "SingersApp";

	/**
	 * Simply selects the home view to render by returning its name.
	 */
	@RequestMapping(value = "/", method = RequestMethod.GET)
	public String home(Locale locale, Model model) {
		System.out.println("Home Page Requested,  locale = " + locale);
		
		Date date = new Date();
		DateFormat dateFormat = DateFormat.getDateTimeInstance(DateFormat.LONG, DateFormat.LONG, locale);

		String formattedDate = dateFormat.format(date);

		model.addAttribute("serverTime", formattedDate);
		
		model.addAttribute("appName", appName);

		return "home";
	}

}

src/main/java/it/univpm/advprog/singers/controller/InstrumentController.java
package it.univpm.advprog.singers.controller;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;

import it.univpm.advprog.singers.model.entities.Instrument;
import it.univpm.advprog.singers.services.InstrumentService;

@RequestMapping("/instruments")
@Controller
public class InstrumentController {
	private final Logger logger = LoggerFactory.getLogger(InstrumentController.class);
	
	private InstrumentService instrumentService;
//	private MessageSource messageSource;


	// handle urls like this:
	// 
	// http://localhost/.../instruments/list
	// http://localhost/.../instruments/list?message=Errore%20parametri%20operazione
	//
	@GetMapping(value = "/list")
	public String list(@RequestParam(value = "message", required=false) String message, Model uiModel) {
		logger.info("Listing instruments");
		List<Instrument> allInstruments = this.instrumentService.findAll();
		
		uiModel.addAttribute("instruments", allInstruments);
		uiModel.addAttribute("numInstruments", allInstruments.size());
		
		// TODO ricevere un parametro via GET (es. per messaggio di esito operazione)
		uiModel.addAttribute("message", message);
		
		return "instruments/list";
	}
	
	@GetMapping(value = "/{instrumentId}/delete")
	public String delete(@PathVariable("instrumentId") String instrumentId) {
		this.instrumentService.delete(instrumentId);
		
		return "redirect:/instruments/list";
	}
	
	@GetMapping(value = "/add")
	public String add(Model uiModel) {
		
		uiModel.addAttribute("instrument", new Instrument());
		
		return "instruments/form";
	}

	@GetMapping(value="/{instrumentId}/edit")
	public String edit(@PathVariable("instrumentId") String instrumentId, 
			Model uiModel) {
		
		Instrument i = this.instrumentService.findById(instrumentId);
		uiModel.addAttribute("instrument", i);
		
		return "instruments/form";
	}

	private void sanitizeId(String instrumentId) {
		if (instrumentId.contains("/")) {
			throw new RuntimeException("Id strumento malformato");
		}
	}
	
	@PostMapping(value="/save")
	public String save(@ModelAttribute("instrument") Instrument instrument, 
			BindingResult br, Model uiModel) {
		
		try {
			this.sanitizeId(instrument.getInstrumentId());
			
			this.instrumentService.update(instrument);
			
			String strMessage = "Strumento (" + instrument.getInstrumentId() + "," + instrument.getFamily() + ") salvato correttamente";
			//uiModel.addAttribute("message", strMessage);
			
			return "redirect:/instruments/list?message=" + strMessage;
		} catch (RuntimeException e) {
			return "redirect:/instruments/list?message=" + e.getMessage();
		}
	}
	
	@Autowired
	public void setInstrumentService(InstrumentService instrumentService) {
		this.instrumentService = instrumentService;
	}
}

WebContent/WEB-INF/views/singers/form.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@taglib prefix="form" uri="http://www.springframework.org/tags/form" %>

		<%-- NB il tag <c:url ... /> non puo` comparire dentro <form:form ... , per questa ragione
		lo usiamo "fuori" da esso, e ne memorizziamo il risultato in una variabile ausiliaria --%>
		<c:url value="/singers/save" var="action_url" />
        <form:form method="POST" action="${action_url}" modelAttribute="newSinger">
             <table>
<%--
				<c:if test="${newSinger.id > 0}">

				<tr>
                    <td><form:label path="id">Id</form:label></td>
                    <td><form:input path="id" /></td>
                </tr>
				
				</c:if>
 --%>
               <tr>
                    <td><form:label path="firstName">First name</form:label></td>
                    <td><form:input path="firstName"/></td>
                </tr>
				<tr>
                    <td><form:label path="lastName">Last name</form:label></td>
                    <td><form:input path="lastName"/></td>
                </tr>
				<tr>
                    <td><form:label path="birthDate">Birth date</form:label></td>
                    <td><form:input path="birthDate"/></td>
                </tr>
<%--
				<tr>
					<td><form:label path="version">Version</form:label></td>
                    <td><form:input path="version"/></td>
				</tr>
--%>
				<tr>
					<td><form:hidden path="id" /></td>
					<td><form:hidden path="version" /></td>
				</tr>
                <tr>
                    <td><input type="submit" value="Submit"/></td>
                </tr>

            </table>
		</form:form>

WebContent/WEB-INF/views/singers/link_choose.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>

    
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>User Home Page</title>
<link href="<c:url value="/css/singers.css" />" rel="stylesheet">
</head>
<body>
<a href="<c:url value="/" />">Home</a>
<hr/>
Numero di cantanti: ${fn:length(singers)}. Numero di strumenti: ${fn:length(instruments)}.
<h1>Scegli</h1>
<form method="POST" action="<c:url value="/singers/link" />">
<table>
<tr>
<td>Cantanti</td>
<td>
<select name="singer">
<c:forEach items="${singers}" var="s">
<option value="${s.id}">${s.fullName}</option> 
</c:forEach>
</select>
</td>
</tr>
<tr>
<td>Strumenti</td>
<td>
<select name="instrument">
<c:forEach items="${instruments}" var="i">
<option value="${i.instrumentId}">${i.name} (${i.family})</option> 
</c:forEach>
</select>
</td>
</tr>
</table>
<input type="submit" value="Scegli"/>
</form>
</body>
</html>

WebContent/WEB-INF/views/singers/list.jsp
<%@page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>

    
<!-- questo non e` un commento di vista: ${mySecret} -->
<%--questo e` un commento di vista (JSTL) ${mySecret} --%>
<%-- NB questo codice non funziona:

Numero di cantanti: ${singers.size()}. <c:if test="${singers.size() ge 0}">Sono pochi!</c:if>

Invocare un metodo e` una di quelle operazioni piu` adatte ad un controller che non ad una vista. Opzioni disponibili:

- chiamare il metodo nel controller, salvare il risultato in un attributo del modello passato alla vista
- creare un tag personalizzato che "wrappi" l'invocazione del metodo desiderato, e richiamare il tag nella vista
- aggirare il limite con <jsp:useBean ...

 --%>
<%--Numero di cantanti censiti: ${fn:length(singers)}. <c:if test="${fn:length(singers) lt 10}">Si può fare di più!</c:if>  --%>
Numero di cantanti: ${numSingers}. <c:choose><c:when test="${numSingers lt 0}">Problemi di connessione al DB?</c:when><c:when test="${numSinger lt 10}">Sono pochi!</c:when></c:choose>
<h1>Elenco</h1>
<table>
<thead><td></td><td>First name</td><td>Last name</td><td>Birth date</td><td></td><td>Instruments</td></thead>
<c:forEach items="${singers}" var="s">
<tr><td>[<a href="<c:url value="/singers/${s.id}/edit/" />">+</a>]</td><td>${s.firstName}</td><td>${s.lastName}</td><td>${s.birthDate}</td><td>[<a href="<c:url value="/singers/${s.id}/delete/"/>">X</a>]</td>
	<td>
	Strumenti del cantante: ${fn:length(s.instruments)}
	<ul>
	<c:forEach items="${s.instruments}" var="i">
	<li>${i.instrumentId} - ${i.name} [<a href="<c:url value="/singers/${s.id}/instrument/${i.instrumentId}/unlink/"/>">X</a>]</li>
	</c:forEach>
	</ul>
	</td></tr>
</c:forEach>
</table>
<hr/>
<a href="<c:url value="/singers/add" />">Aggiungi cantante</a>